name: Versions Update

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/version_update.yml'
  schedule:
    # Run once on the first of the month
    - cron: '45 0 1 * *'

jobs:
  update:
    name: Versions Update
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 22
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache local .m2
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up maven
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-distribution: 'temurin'
          java-version: '22'
          maven-version: '3.9.8'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy docker containers
        id: docker_deploy
        run: docker compose --file docker-compose-dev.yml up --build --detach

      - name: Update Maven project versions
        run: mvn versions:update-properties

      - name: Run tests and build
        run: mvn clean install -Dall

      - name: Run linters and unit/integration tests
        id: application_tests
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn clean install -Dall
        continue-on-error: true

      - name: Commit and push changes
        if: steps.application_tests.outcome == 'success'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m 'Updating versions'
          git push

      - name: Shut down docker containers
        run: docker compose --file docker-compose-dev.yml down
        if: steps.docker_deploy.outcome == 'success'